// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/add_sync": {
            "post": {
                "description": "метод для добавления новой синхронизации",
                "tags": [
                    "Post"
                ],
                "summary": "addNewSync",
                "parameters": [
                    {
                        "description": "body example",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/api.InputDataApi"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/all_sync": {
            "get": {
                "description": "some description",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Get"
                ],
                "summary": "allSync",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.StateAnswer"
                        }
                    }
                }
            }
        },
        "/start-allSync": {
            "post": {
                "description": "метод для старта всех синхронизаций",
                "tags": [
                    "Post"
                ],
                "summary": "startAllSync",
                "responses": {}
            }
        },
        "/start_sync": {
            "post": {
                "description": "метод для старта приостановленной синхронизации",
                "tags": [
                    "Post"
                ],
                "summary": "startSync",
                "parameters": [
                    {
                        "description": "body example",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/api.InputDataApi"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/stop_sync": {
            "post": {
                "description": "метод для остановки синхронизации",
                "tags": [
                    "Post"
                ],
                "summary": "stopSync",
                "parameters": [
                    {
                        "description": "body example",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/api.InputDataApi"
                        }
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "api.InputDataApi": {
            "type": "object",
            "properties": {
                "data_base": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "offset": {
                    "type": "string"
                },
                "table": {
                    "type": "string"
                }
            }
        },
        "api.StateAnswer": {
            "type": "object",
            "properties": {
                "data": {},
                "err": {},
                "info": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "sync_service",
	Description:      "This is a sample server Petstore server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
