basePath: /
definitions:
  api.InputDataApi:
    properties:
      data_base:
        type: string
      is_active:
        type: boolean
      offset:
        type: string
      table:
        type: string
    type: object
  api.StateAnswer:
    properties:
      data: {}
      err: {}
      info:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: This is a sample server Petstore server.
  title: sync_service
  version: "1.0"
paths:
  /add_sync:
    post:
      description: метод для добавления новой синхронизации
      parameters:
      - description: body example
        in: body
        name: request
        schema:
          $ref: '#/definitions/api.InputDataApi'
      responses: {}
      summary: addNewSync
      tags:
      - Post
  /all_sync:
    get:
      consumes:
      - application/json
      description: some description
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.StateAnswer'
      summary: allSync
      tags:
      - Get
  /start-allSync:
    post:
      description: метод для старта всех синхронизаций
      responses: {}
      summary: startAllSync
      tags:
      - Post
  /start_sync:
    post:
      description: метод для старта приостановленной синхронизации
      parameters:
      - description: body example
        in: body
        name: request
        schema:
          $ref: '#/definitions/api.InputDataApi'
      responses: {}
      summary: startSync
      tags:
      - Post
  /stop_sync:
    post:
      description: метод для остановки синхронизации
      parameters:
      - description: body example
        in: body
        name: request
        schema:
          $ref: '#/definitions/api.InputDataApi'
      responses: {}
      summary: stopSync
      tags:
      - Post
swagger: "2.0"
