basePath: /
definitions:
  main.InputDataApi:
    properties:
      data_base:
        type: string
      is_active:
        type: boolean
      offset:
        type: string
      table:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: This is a sample server Petstore server.
  title: sync_service
  version: "1.0"
paths: {}
swagger: "2.0"
